### ISSUE TITLE
Extensibility

### ISSUE THREAD

**Issue by Vignesh1115** [buildAI/aliensOnEarth#2]
1) Consider a situation where we might want to take the details of multiple aliens and then finally decide if the details have to be exported to any format or none at all. Would your current code be able to handle it?
2) Consider a situation where we want the blood color of the alien in Hexadecimal value only in the Pdf file or RGB value in the Text file. Could we do that currently?
You could review Part A once more and get back to us if you need any further clarifications?

**Comment by buildAI** [comment]
@Vignesh1115 In the way I perceive I've got few queries here
In the first case I can actually add new function where the file format is defined and that can lead to a new output and considering the case of replacing the if statement I can replace it with another method instead giving n number of if statements and ignore the export data at all adding it as an option.

In the second case this is like adding a new feature which should just convert the string colour of the code to RGB or HxD I can do this by adding some logic but do you actually want each parameter as separate variable so that each data can be used for further reference?

Please let me if my perception was right or wrong

**Comment by Vignesh1115** [comment]
@buildAI 

1) Currently you are taking input about the properties and converting them into a single string. Wouldn't it be better if you could figure out a way to group a set of related properties? If that's possible it would be easier to allow either a single or a million alien details being captured.

2) Again this is an issue with how you have designed the code. Currently we are getting a single string being passed around to PDF and text file creator. If we wanted to display certain properties in a different manner in each of the formats (Blood color as hexadecimal, RGB or CMYK values), could we currently do that?

Please try addressing the current issue instead of combining them.

**Comment by buildAI** [comment]
oh okay! I got the point^ I can fix both the issues. Since I'm even working with project at geekskool I can fix the issue with in 48 hours. I would keep myself up to fix the issue even before 48 hours if possible.

**Comment by Vignesh1115** [comment]
@buildAI Thanks for the update. Looking forward to see the code in a couple of days.

**Comment by buildAI** [comment]
@Vignesh1115 Apologies for the delay. Please check the repository and let me know if the issues are solved.
